export default {
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",
  CREATE_PROFESSOR: "CREATE_COURSE",
  UPDATE_PROFESSOR: "UPDATE_COURSE",
  DELETE_PROFESSOR: "DELETE_COURSE",
  LOAD_PROFESSORS: "LOAD_PROFESSORS"
}